services:
  laravel:
    build:
      context: ./ticketApi
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./ticketApi:/var/www/html
    ports:
      - "8000:8000"

  quasar:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quasar-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "9000:9000"
